{
    'name': 'Hospital Management',
    'author': 'Moamen Sherif Abdelkader',
    'category': 'Hospital',
    'sequence': -100,
    'version': '18.0.1.0',
    'summery': 'Hospital management system',
    'depends': ['base',
                'account',
                'mail',
                'product',
                'purchase',
                'stock',
                'sale_management',
                'account_invoice_extract',
                'report_xlsx',
                ],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/patient_tag_data.xml',
        'data/patient.tag.csv',
        'data/mail_template_data.xml',
        'reports/sale_order_report.xml',
        'wizard/cancel_appointment_view.xml',
        'wizard/appointment_report_view.xml',
        'wizard/patient_report_view.xml',
        'views/patient_view.xml',
        'views/female_patient_view.xml',
        'views/kid_patient_view.xml',
        'views/appointment_view.xml',
        'views/patient_tag_view.xml',
        'views/sale_order_view.xml',
        'views/account_move_view.xml',
        'views/operation_view.xml',
        'views/res_config_settings_views.xml',
        'views/res_partner_category.xml',
        'views/product_template.xml',
        'views/menu.xml',
        'reports/patient_card_cg.xml',
        # 'reports/patient_card_gg.xml',
        # 'reports/patient_appointment_gg.xml',
        'reports/patient_appointment_cg.xml',
        'reports/patient_appointment_wizard_gg.xml',
        'reports/patient_wizard_gg.xml',
        'reports/report.xml',
    ],
    'demo': [
    ],
    'application': True,
}
