from . import patient
from . import appointment
from . import patient_tag
from . import sale_order
from . import res_config_settings
from . import operation
from . import groups
from . import account_move
from . import product_template
from . import stock_move